pub const Action = enum {
    move_up,
    move_down,
    move_left,
    move_right,
    page_up,
    page_down,

    quit,

    start_search,
    clear_search,

    kill_term,
    kill_force,
    pause_process,
    resume_process,

    sort_by_pid,
    sort_by_name,
    sort_by_cpu,
    sort_by_mem,
    toggle_expand,
    toggle_expand_all,
    jump_top,
    jump_bottom,
    exit_search_view,
    show_help,
    open_detail,
    close_detail,
    focus_left,
    focus_right,
    toggle_detail_view,
    toggle_detail_section,
    toggle_cpu_overlay,
    toggle_temp_unit,
    cycle_storage_detail,
    toggle_mount_filter,
    toggle_network_mode,
    toggle_protocol_filter,
    toggle_preserve_log,
    confirm_dialog_yes,
    confirm_dialog_no,
    toggle_select,
    clear_selections,
    dashboard_cpu,
    dashboard_mem,
};
